syntax = "proto3";

// Опции для генерации Java-кода
option java_multiple_files = true;
option java_package = "org.eldir.shared.grpc";
option java_outer_classname = "AuthProto";

package eldir;

// Сервис для аутентификации пользователей
service AuthService {
  // Производит вход пользователя в систему
  rpc Login(LoginRequest) returns (LoginResponse);

  // (Опционально) Регистрирует нового пользователя
  rpc Register(RegisterRequest) returns (RegisterResponse);
}

// ---- Сообщения для RPC-методов ----

// Запрос на вход в систему
message LoginRequest {
  string login = 1;
  string password = 2;
}

// Ответ сервера после успешного входа
message LoginResponse {
  // Самое главное - JWT токен, который клиент должен сохранить
  // и использовать для всех последующих запросов.
  string access_token = 1;
  string user_id = 2; // ID пользователя, может пригодиться клиенту
}

// Запрос на регистрацию
message RegisterRequest {
  string email = 1;
  string password = 2;
  // Можно передать и другие начальные данные
  map<string, string> initial_attributes = 3;
}

// Ответ после регистрации
message RegisterResponse {
  string user_id = 1; // ID созданного пользователя
  string message = 2;
}

service UserService {
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse);
  rpc UpdateUserClearance(UpdateUserClearanceRequest) returns (UpdateUserClearanceResponse);
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);
}

message ListUsersRequest {} // Пустой, дай всех

message UserDto {
  string id = 1;
  string login = 2;
  string clearance_level = 3; // "ACCESS_SECRET" и т.д.
}

message ListUsersResponse {
  repeated UserDto users = 1;
}

message UpdateUserClearanceRequest {
  string login = 1;
  string new_clearance_level = 2; // ENUM строкой
}

message UpdateUserClearanceResponse {
  bool success = 1;
  string message = 2;
}

message CreateUserRequest {
  string login = 1;
  string password = 2;
  string clearance_level = 3;
}

message CreateUserResponse {
  bool success = 1;
  string message = 2;
  string user_id = 3;
}