spring.application.name=eldir

spring.datasource.url=jdbc:postgresql://localhost:5432/eldir_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# gRPC Server configuration
grpc.server.port=9090

logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
grpc.security.auth.enabled=false
grpc.security.enabled=false